### ISSUE TITLE
Can't create AdminUser

### ISSUE THREAD

**Issue by aEvgenn** [internetee/registry#1019]
I am trying to create a first user to login. But I get an error.
```
root@32bb08ce7340:/opt/webapps/app# rake bootstrap --trace
** Invoke bootstrap (first_time)
** Execute bootstrap
rake aborted!
NameError: uninitialized constant AdminUser
/opt/webapps/app/lib/tasks/bootstrap.rake:3:in `block in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/usr/local/bundle/gems/airbrake-6.0.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
Tasks: TOP => bootstrap

```
And need fix README.md (remove colon in the string):
bundle exec rake:bootstrap -> bundle exec rake bootstrap

**Comment by maciej-szlosarczyk** [comment]
@aEvgenn, you can pull the newer master version and the bootstrap task should run normally.

**Comment by aEvgenn** [comment]
@maciej-szlosarczyk thx for fast fix
It's works
