### ISSUE TITLE
Bank autocheck: NoMethodError: undefined method `text' for nil:NilClass

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1475]
We have quite many errors like these in the logs:

```
rake aborted!
NoMethodError: undefined method `text' for nil:NilClass
/home/registry/registry/shared/bundle/ruby/2.4.0/bundler/gems/lhv-e211516bc5ff/lib/lhv/connect_api/messages/credit_debit
_notification.rb:26:in `block in credit_transactions'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:238:in `block in each
'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `upto'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `each'
/home/registry/registry/shared/bundle/ruby/2.4.0/bundler/gems/lhv-e211516bc5ff/lib/lhv/connect_api/messages/credit_debit
_notification.rb:18:in `credit_transactions'
/home/registry/registry/releases/110/lib/tasks/invoices/process_payments.rake:23:in `block (3 levels) in <top (required)
>'
/home/registry/registry/releases/110/lib/tasks/invoices/process_payments.rake:20:in `each'
/home/registry/registry/releases/110/lib/tasks/invoices/process_payments.rake:20:in `block (2 levels) in <top (required)
>'
/home/registry/registry/shared/bundle/ruby/2.4.0/gems/airbrake-9.4.5/lib/airbrake/rake.rb:17:in `execute'
/home/registry/registry/releases/110/vendor/bundle/ruby/2.4.0/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
bin/bundle:3:in `load'
bin/bundle:3:in `<main>'
Tasks: TOP => invoices:process_payments
(See full trace by running task with --trace)
```

should be handeled better so it would be clearer what might be the cause of this.

**Comment by vohmar** [comment]
fixed by https://github.com/internetee/lhv/pull/1
requires gem update on registry side

**Comment by vohmar** [comment]
waiting for gem update on registry side
