### ISSUE TITLE
Registrar: ID-card authetnication fails

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#1669]
Error message:

```
Started POST "/registrar/id" for IP at 2020-09-01 11:18:49 +0300
Processing by Registrar::SessionsController#id_card as HTML
Parameters: {"authenticity_token"=>"RSrszl1Fr1zqyo2EirooS42MshyrdAESw+LBNyvSmQTtghv+g8dBFt+IbjaiQT3UkF4xTrT6wXL8Qjhkv7HSdQ=="}
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms | Allocations: 777)
#012[HASH] [registrar] [IP] NoMethodError (undefined method `force_encoding' for nil:NilClass):#012[HASH] [registrar] [IP]   #012[HASH] [registrar] [IP] lib/devise/strategies/id_card_authenticatable.rb:31:in `first_name'#012[HASH] [registrar] [IP] lib/devise/strategies/id_card_authenticatable.rb:23:in `id_card'#012[HASH] [registrar] [IP] lib/devise/strategies/id_card_authenticatable.rb:10:in `authenticate!'#012[HASH] [registrar] [IP] app/controllers/registrar/sessions_controller.rb:195:in `user_for_paper_trail'
```

**Comment by vohmar** [comment]
no issue here - user's browser restart fixed the problem
