### ISSUE TITLE
Admin - manual binding new bank transaction: undefined method `settings' for nil:NilClass

### ISSUE THREAD

**Issue by DinSmol** [internetee/registry#2095]
When trying to bind manually new bank transaction in the admin panel, there is an error: undefined method `settings' for nil:NilClass

Reproducing the error step by step:

Go settings and click on Invoices
Select some unpaid invoice
Click to "Payment received"
Click to save
Click to add in Bank Transaction sections
Fill in the fields: fill in the reference_number field with wrong value
Click to save
Fill in the Binded invoice field and click "Bind manually"

**Comment by DinSmol** [comment]
added test for reproducing the issue https://github.com/internetee/registry/tree/2095-undefined-method-settings

**Comment by OlegPhenomenon** [comment]
I repeated the steps, another error appeared on the local environment:

![Screenshot from 2021-08-09 16-39-23](https://user-images.githubusercontent.com/37714103/128715466-8100ebda-9f66-4554-9cb4-88ff3b360fd8.png)

```
NoMethodError (undefined method `paid?' for nil:NilClass):
  
app/models/bank_transaction.rb:71:in `validate_invoice_data'
app/models/bank_transaction.rb:63:in `bind_invoice'
app/controllers/admin/bank_transactions_controller.rb:37:in `bind'
```

I tried to repeat the same thing on the staging, the following message was displayed in the logs:
```
Aug  9 16:31:04 staging st-adm.infra.tld.ee[23547]: Completed 500 Internal Server Error in 12ms (ActiveRecord: 1.7ms | Allocations: 2767)
Aug  9 16:31:04 staging st-adm.infra.tld.ee[23547]: NoMethodError (undefined method `paid?' for nil:NilClass):#012  #012app/models/bank_transaction.rb:71:in `validate_invoice_data'#012app/models/bank_transaction.rb:63:in `bind_invoice'#012app/controllers/admin/bank_transactions_controller.rb:37:in `bind'
````

The reason may also be in setting up test payment gateways, because as far as I know, there is no such problem in production.
