### ISSUE TITLE
Fix failing specs

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#233]
```
 10) Domain with valid attributes should validate uniqueness of tech contacts
      Failure/Error: @domain = Fabricate(:domain)
      NoMethodError:
        undefined method `json=' for #<Whois::Record:0x007f000fc5d8a0>
      # ./app/models/whois_record.rb:115:in `update_whois_server'
      # ./app/jobs/update_whois_record_job.rb:25:in `update_domain'
      # ./app/jobs/update_whois_record_job.rb:15:in `block in run'
      # ./app/jobs/update_whois_record_job.rb:12:in `each'
      # ./app/jobs/update_whois_record_job.rb:12:in `run'
      # ./app/models/domain.rb:716:in `update_whois_record'
      # ./spec/models/domain_spec.rb:78:in `block (3 levels) in <top (required)>'
      # -e:1:in `<main>'

```

**Comment by artur-beljajev** [comment]
I have fixed this by re-creating db structure, therefore no fix is needed.
