### ISSUE TITLE
Auto emails on expiry of pending update fail

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#292]
sending emails on expiration of pending update requests fail

sample error message in log:
```
"DomainMailer", "pending_update_expired_notification_for_new_registrant", 57413

Last Error  

no implicit conversion of Symbol into Integer
/home/registry/registry/releases/61/app/mailers/domain_mailer.rb:148:in `[]'
/home/registry/registry/releases/61/app/mailers/domain_mailer.rb:148:in `compose_from'
/home/registry/registry/releases/61/app/mailers/domain_mailer.rb:47:in `pending_update_expired_notification_for_new_registrant'
```

another one
```
Dec  1 13:48:42 test-reg ADMIN[11192]: Sent mail to  (3.5ms)
Dec  1 13:48:42 test-reg ADMIN[11192]: {"lib":"que","hostname":"test-reg","pid":11192,"thread":70159412178840,"event":"job_errored","error":{"class":"ArgumentError","message":"An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address."},"job":{"queue":"","priority":100,"run_at":"2016-12-01T11:48:41.115+00:00","job_id":8094,"job_class":"RegistrantChangeExpiredEmailJob","args":[592],"error_count":1}}
```

**Comment by vohmar** [comment]
it seems that the email job is created too late in the process so that when the email sending attempt is done the actual pending process is already expired and the job does not find the address to send the notice to.

**Comment by teadur** [comment]
Log: Send RegistrantChangeMailer#expired email for domain xxxxx.ee (#xxxxx) to
By the time RegistrantChangeMailer is invoked domain.new_registrant_email is already nil
