### ISSUE TITLE
Registrant: error on login to portal

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#390]
A user reported issues with logging into the portal for registrants. He has used the portal previously

![image001](https://cloud.githubusercontent.com/assets/7734747/23454095/ce202708-fe73-11e6-88da-17a97bc7eb6e.png)

log:
```
[11:22:13] <ratMin> Feb 28 22:40:09 reg-l-rant REGISTRANT[28116]: [registrant] [f54c3d58-b3d6-4f5f-8245-6c36337d367e] [217.159.129.139] #012
[11:22:16] <ratMin> NoMethodError (undefined method `element_children' for nil:NilClass):#012  app/models/soap/arireg.rb:99:in `associated_b
[11:22:20] <ratMin> usinesses'#012  app/models/business_registry_cache.rb:62:in `fetch_by_ident_and_cc'#012  app/models/business_registry_ca
[11:22:23] <ratMin> che.rb:49:in `fetch_associated_domains'#012  app/controllers/registrant/domains_controller.rb:58:in `domains'#012  app/c
[11:22:27] <ratMin> ontrollers/registrant/domains_controller.rb:7:in `block in index'#012  app/controllers/registrant/domains_controller.rb:
[11:22:30] <ratMin> 74:in `normalize_search_parameters'#012  app/controllers/registrant/domains_controller.rb:6:in `index'#012  config/initi
[11:22:34] <ratMin> alizers/eis_custom_flash.rb:9:in `call'
```

**Comment by artur-beljajev** [comment]
When exactly did it happen? I don't see the url. Also, please provide formatted log, the one provided is unreadable.

**Comment by artur-beljajev** [comment]
mobile-id

**Comment by artur-beljajev** [comment]
How many users experienced this issue? It seems like some error while trying to parse business registry's response. One of the possible reasons can be that the registry was unavailable for some time and during this time some unexpected response was generated. 

Some folks report gem incompatible issues: https://github.com/savonrb/wasabi/issues/61

**Comment by artur-beljajev** [comment]
To investigate this issue further I need to setup business registry access on localhost, which my be time consuming. Confirm this.

**Comment by teadur** [comment]
Bussiness registry access is whitelist based, so you cannot access it from your home ip.
In theory you could use our interna proxy for that ( would require vpn to be connected ) so it makes more sense to test/dev it in staging rather then "localhost"

**Comment by vohmar** [comment]
this seems to have been some temporary type of error, the user does not have this any more. But better error handling would still be nice if possible. May have been some error on SK's side.
