### ISSUE TITLE
REPP: bulk transfer returns code 204 on success

### ISSUE THREAD

**Issue by vohmar** [internetee/registry#693]
the return code for successful transfer is 204 ie no contect to gether with empty response in log as well (/admin/repp_logs/????).

For successful transfer the return code should be 200 together with message for example "5 domainnames successfully transfered"

**Comment by artur-beljajev** [comment]
Do I get it right that the point is to have some report of domains transferred?

**Comment by vohmar** [comment]
the goal is to return more meaningful answer. As discussed can be machine oriented message ie "transfered domains = 5"

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/blob/189129ec4865cfe80946cd5dfa42aa6eb3392b42/app/models/epp/domain.rb#L833

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/blob/189129ec4865cfe80946cd5dfa42aa6eb3392b42/app/models/epp/domain.rb#L816

**Comment by artur-beljajev** [comment]
https://github.com/internetee/registry/blob/189129ec4865cfe80946cd5dfa42aa6eb3392b42/app/models/epp/domain.rb#L629

**Comment by artur-beljajev** [comment]
Stuck to http://jsonapi.org/ with the exception that ID (which is required) is not returned. Returning ID requires more effort: we need to decide what is considered as ID in REST API.

**Comment by vohmar** [comment]
bulk transfer gave absolutely no feedback in regsitrar's portal whether it failed or succeeded. 
Admin REPP log entry is also uninformative: https://staging-adm.infra.tld.ee:444/admin/repp_logs/551

```
{
  "data": [
    {
      "type": "domain_transfer"
    },
    {
      "type": "domain_transfer"
    },
    {
      "type": "domain_transfer"
    },
    {
      "type": "domain_transfer"
    }
  ]
}
```

**Comment by vohmar** [comment]
Invalid test results:
Success message in registrars' portal UI: Domains have been successfully transferred.
Expected result is: 4 domainnames have been successfully transferred

PS
If possible the message of response code 400 should also have information about number of domains successfully transfered in addition to naming the ones that were not.

**Comment by artur-beljajev** [comment]
1. Notification message in registrar area is updated
2. Current implementation allows partial update, meaning that you get response code of `400`, even though some domains have been transferred.

This needs more thought, as `400` is actually incorrect. `207` might be a better choice (https://stackoverflow.com/questions/45442847/rest-api-response-in-partial-success). I hadn't enough time to think about API in general. And I am not sure it is worth it, given that brand new API is on the way.

**Comment by vohmar** [comment]
207 looks like a good way to handle partial success - will make it into separate ticket.  Complete success/failure requirement is not justified.

**Comment by vohmar** [comment]
epp login generates internal error

`Feb 26 12:57:57 staging EPP[7271]: [ddfbb18c-d5a3-44d1-a7e6-48631e8f4183] [127.0.0.1] FROM-EPP-RESCUE: ERROR:  column epp_sessions.user_id does not exist#012LINE 1: SELECT COUNT  FROM "epp_sessions" WHERE "epp_sessions"."us...#012`

looks like a problem with db structure

**Comment by artur-beljajev** [comment]
Check that branch has been deployed properly.

I checked that column, and it is present https://github.com/internetee/registry/blob/9697752823e3dd302788f62a02d6e883af411278/db/structure.sql#L1056

**Comment by teadur** [comment]
@artur-beljajev 
it seems that the field is added to structure.sql here:
https://github.com/internetee/registry/commit/ba341ee41125d381fb9da06b51d13b16a48113e7#diff-f9ae8314082d8229b38da27dd6c2642d

But i can't find migration what adds this column.

**Comment by vohmar** [comment]
tried to transfer list on 34 domains and got internal error in response - nothing is logged in REPP log.

**Comment by teadur** [comment]
```
Feb 26 17:33:17 staging EPP[2093]: [staging-repp.infra] [bdd481a8-f525-4444-bec9-a684a934d529] [x.x.x.x] #012ActiveRecord::RecordInvalid (Validation failed:
 Nameservers Nameservers are invalid):#012  app/models/concerns/domain/transferable.rb:18:in `block in transfer'#012  app/models/concerns/domain/transferable.rb:16
:in `transfer'#012  app/models/domain_transfer.rb:66:in `block in approve'#012  app/models/domain_transfer.rb:61:in `approve'#012  app/models/domain_transfer.rb:23
:in `request'#012  app/api/repp/domain_transfers_v1.rb:28:in `block (3 levels) in <class:DomainTransfersV1>'#012  app/api/repp/domain_transfers_v1.rb:21:in `each'#
012  app/api/repp/domain_transfers_v1.rb:21:in `block (2 levels) in <class:DomainTransfersV1>'
```

**Comment by artur-beljajev** [comment]
#728 to the rescue
